# Generated by Django 4.0.3 on 2022-03-31 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.IntegerField()),
                ('rg', models.IntegerField(blank=True)),
                ('data_nasc', models.DateField(blank=True)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('cep', models.CharField(blank=True, max_length=15)),
                ('logadouro', models.CharField(blank=True, max_length=100)),
                ('numero', models.IntegerField(blank=True)),
                ('bairro', models.CharField(blank=True, max_length=50)),
                ('complemento', models.CharField(blank=True, max_length=50)),
                ('uf', models.TextField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], default=0, max_length=2)),
                ('cidade', models.CharField(blank=True, max_length=200)),
                ('tipo_cliente', models.TextField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('PROSPECCAO', 'Prospecção')], default=0, max_length=15)),
            ],
        ),
    ]
