# Generated by Django 4.0.3 on 2022-03-31 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nasc', models.DateField(blank=True)),
                ('especie', models.CharField(max_length=20)),
                ('raca', models.CharField(blank=True, max_length=15)),
                ('cor', models.CharField(blank=True, max_length=100)),
                ('idade', models.IntegerField(blank=True)),
                ('porte', models.TextField(choices=[('MICRO', 'Micro'), ('PEQUENO', 'Pequeno'), ('MEDIO', 'Médio'), ('GRANDE', 'Grande'), ('GIGANTE', 'Gigante')], default=0, max_length=15)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], default=0, max_length=10)),
            ],
        ),
    ]
